services:
  nginx:
    build: .
    restart: unless-stopped
    env_file: .env.vars
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - rocks_rocks_staticfiles:/var/www/rocks/static
      - sensorplaces_sensors-static:/var/www/sensors/static
      - type: bind
        source: /var/www/sites
        target: /var/www/sites
        read_only: true
    networks:
      - webhost

volumes:
  rocks_rocks_staticfiles:
    external: true
  sensorplaces_sensors-static:
    external: true

networks:
  webhost:
    external: true
