services:
  nginx:
    build: .
    restart: unless-stopped
    env_file: .env.vars
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/logs:/var/log/nginx
      - type: bind
        source: /var/www/sites
        target: /var/www/sites
        read_only: true
    networks:
      - webhost
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

networks:
  webhost:
    external: true
