services:
  nginx:
    build: .
    restart: unless-stopped
    env_file: .env.vars
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # - rocks_rocks_staticfiles:/var/www/informs/static

# volumes:
#   rocks_rocks_staticfiles:
#     external: true

networks:
  default: 
    name: webhost
    external: true
