version: '3'

services:
  nginx:
    environment:
      CERTBOT_DOMAINS: "${CERTBOT_FQDN:-.}"
      CERTBOT_EMAIL: "${CERTBOT_EMAIL:-.}"
      NGINX_FQDN: "${NGINX_FQDN:-.}"
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - surveyor_surveyor_staticfiles:/var/www/surveyor/static
    # networks:
    #   - webhost

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot

volumes:
  surveyor_surveyor_staticfiles:
    external: true

networks:
  default: 
    name: webhost
    external: true