# HTTP Server Block
server {
    listen 80;
    server_name @{FQDN};

    # Redirect all HTTP requests to HTTPS, with exceptions for ACME challenge and webhooks
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /webhook/ {
        proxy_set_header Host $host;
        proxy_pass http://@{UPSTREAM_HOST}:@{PORT};
        proxy_read_timeout 60;
        # Add necessary headers for the webhook endpoint
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS Server Block
server {
    listen 443 ssl;
    http2 on;
    server_name @{FQDN};

    ssl_certificate /etc/letsencrypt/live/@{FQDN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/@{FQDN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /root/resources/nginx_logging.conf;
    
    location /static/ {
        alias /var/www/@{APPNAME}/static/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://@{UPSTREAM_HOST}:@{PORT};
        # All other configuration (security headers, proxy settings, etc.)
    }

    # Other location blocks like /static/, /ws/, etc. go here
}
