# HTTP Server Block
server {
    listen 80;
    server_name @{FQDN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS Server Block
server {
    listen 443 ssl;
    http2 on;
    server_name @{FQDN};

    ssl_certificate /etc/letsencrypt/live/@{FQDN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/@{FQDN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /root/resources/nginx_logging.conf;

    root @{SITEPATH};
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
        # All other configuration
    }
} 
