server {

    listen 80;
    server_name @{FQDN};
    
    # set a decent default root directory
    root /usr/share/nginx/html/;

    location /himom { 
        return 200 "Hi Mom!";
        add_header Content-Type text/plain;
    }
    # don't log favicon
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
    
    # support certbot folder
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://@{APPNAME}:@{PORT}/;
        proxy_read_timeout 60;

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Xss-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;

        add_header 'Referrer-Policy' 'origin';
        add_header Permission-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()" always;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }

    location /static/ {
        root /var/www/@{APPNAME}/;
        # try_files $uri $uri/ =404;
    }

}
