server {
    listen 80;
    server_name @{FQDN};

    include /root/resources/nginx_security.conf;
    
    root @{SITEPATH};
    index index.html index.htm;

    # Enforce HTTPS (except for ACME challenge)
    set $do_redirect 1;
    if ($request_uri ~ "^/.well-known/acme-challenge/") {
        set $do_redirect 0;
    }
    if ($scheme = "https") {
        set $do_redirect 0;
    }
    if ($do_redirect = 1) {
        return 301 https://$host$request_uri;
    }

    # don't log favicon
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
    
    # support certbot folder
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ =404;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Xss-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Permission-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()" always;
        add_header Strict-Transport-Security $hsts_header always;
        
        # Enable compression
        gzip on;
        gzip_types text/plain text/css application/javascript application/json image/svg+xml;
        gzip_min_length 1000;
        
        # Cache static files
        expires 1h;
        add_header Cache-Control "public, no-transform";
    }
} 
