server {

    listen 80;
    server_name @{FQDN};

    include /root/resources/nginx_security.conf;
    
    # set a decent default root directory
    root /usr/share/nginx/html/;

    # Enforce HTTPS (except for ACME challenge)
    set $do_redirect 1;
    if ($request_uri ~ "^/.well-known/acme-challenge/") {
        set $do_redirect 0;
    }
    if ($scheme = "https") {
        set $do_redirect 0;
    }
    if ($do_redirect = 1) {
        return 301 https://$host$request_uri;
    }

    location /himom { 
        return 200 "Hi Mom!";
        add_header Content-Type text/plain;
    }
    # don't log favicon
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
    
    # support certbot folder
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://@{UPSTREAM_HOST}:@{PORT};
        proxy_read_timeout 60;

        # Security Headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Xss-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Permission-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()" always;
        add_header Strict-Transport-Security $hsts_header always;

        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Compression
        gzip on;
        gzip_types text/plain text/css application/javascript application/json image/svg+xml;
        gzip_min_length 1000;
        gzip_proxied any;
    }

    location /static/ {
        root /var/www/@{APPNAME}/;
        # try_files $uri $uri/ =404;
        
        # Compression for static files too
        gzip on;
        gzip_types text/plain text/css application/javascript application/json image/svg+xml;
        gzip_min_length 1000;
    }

}
